services:
  db_warehouse:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./modules/db/createSQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  warehouse:
    build: .
    ports:
      - "30004:30004"
    depends_on:
      - db_warehouse
    env_file:
      - .env

volumes:
  pg_data: